### ISSUE TITLE
The app has been modified or damaged

### ISSUE THREAD

**Issue by jonathanBieler** [NHDaly/PaddleBattleJL#1]
I just tried to install the last version from the Release page and I'm getting this:

"The app has been modified, and its code does not match the original signed code. The app may be broken or corrupted, or it may have been tampered with. If you think that an app has been damaged or tampered with, you should delete it by dragging it to the Trash."

I guess you have to renew the certificate or something of the sort.

**Comment by pbouffard** [comment]
Presumably what I'm seeing is just another manifestation of the above but FWIW I get:

"“Paddle Battle” is damaged and can’t be opened. You should move it to the Trash."

**Comment by NHDaly** [comment]
Eep! Thanks both of you. Hmmmmm I can't figure out what i did differently for the first release, but I can confirm it's not signed correctly...

It's annoying: it downloaded and opened no-problem for me, even though it wasn't signed correctly! I didn't run the command-line tool to double-check because it worked through the finder, but now I know better! D:

I'm looking into this now though. Thanks!

**Comment by NHDaly** [comment]
Okay! Fixed! :) Please try the latest release, if you could? :)
https://github.com/NHDaly/PaddleBattleJL/releases/tag/v1.0.3

It turned out there were two problems with my `release.sh` script I was using. Unfortunately, I hadn't committed it before i fixed the problem so i can't point at a diff to show you. But basically, there were two problems that resulted from me trying to automate the release process:

1. I wasn't _deleting_ the `.app` on the .dmg before copying my new `.app` onto it. So this meant that any files I've _deleted_ in the app weren't getting deleted in the released version (meaning there was an extra file in the app that wasn't signed). So I fixed that here:
https://github.com/NHDaly/PaddleBattleJL/commit/f2c337971e3a6d1cb4ef47462c5dc6a6a148e5f2#diff-e55bb7573f1110c8b2a6922fe8cccf48R9

2. Apparently even then, when I was using `cp -r` to copy the finished, signed app on the .dmg, it was breaking the signature, because it was "modifying" the signed files (and, i guess, changing their hash). So I had to switch `cp` to `CpMac`, which is the Finder-equivalent copy and it somehow preserves the files completely (I assume by preserving their modified timestamp?):
https://github.com/NHDaly/PaddleBattleJL/commit/7d40de0112078b93be3f40387b48de6dfbc07781


Thanks again for pointing this out!! :) Sorry it took me so long to respond, Jonathan!

**Comment by pbouffard** [comment]
v1.0.3 works! And is pretty great, thank you! Let the Julia indie games revolution begin ;-)

**Comment by NHDaly** [comment]
> Let the Julia indie games revolution begin ;-)

Hahaha 😈

**Comment by NHDaly** [comment]
And thanks for checking it out!! XD
